// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAL5dfYm1whBz_vk-6PBB5wugc9NCEmsc',
    appId: '1:1069987307782:web:9efdfe07c8bbacd7993e87',
    messagingSenderId: '1069987307782',
    projectId: 'gdgoc-firebase',
    authDomain: 'gdgoc-firebase.firebaseapp.com',
    storageBucket: 'gdgoc-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9tG-FS_CfKsawDgGEYTdSi9deozePyvg',
    appId: '1:1069987307782:android:1715c0bf837b833a993e87',
    messagingSenderId: '1069987307782',
    projectId: 'gdgoc-firebase',
    storageBucket: 'gdgoc-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuSzvZP7IRJ7unelpf_ITsHnwINVbtgc',
    appId: '1:1069987307782:ios:91cc63728de27aa3993e87',
    messagingSenderId: '1069987307782',
    projectId: 'gdgoc-firebase',
    storageBucket: 'gdgoc-firebase.firebasestorage.app',
    iosBundleId: 'com.example.gdgocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuSzvZP7IRJ7unelpf_ITsHnwINVbtgc',
    appId: '1:1069987307782:ios:91cc63728de27aa3993e87',
    messagingSenderId: '1069987307782',
    projectId: 'gdgoc-firebase',
    storageBucket: 'gdgoc-firebase.firebasestorage.app',
    iosBundleId: 'com.example.gdgocFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAL5dfYm1whBz_vk-6PBB5wugc9NCEmsc',
    appId: '1:1069987307782:web:12ee22dc7221b870993e87',
    messagingSenderId: '1069987307782',
    projectId: 'gdgoc-firebase',
    authDomain: 'gdgoc-firebase.firebaseapp.com',
    storageBucket: 'gdgoc-firebase.firebasestorage.app',
  );
}
